---
title: "Yakınsama Hipotezine Eleştirel Bakış"
author: 
  - Kağan Güler[^1]
bibliography: ../bibliography/biblio.bib
csl: ../csl/apa-tr.csl
header-includes:
  - \usepackage{polyglossia}
  - \setmainlanguage{turkish}
  - \usepackage{booktabs}
  - \usepackage{caption} 
  - \captionsetup[table]{skip=10pt}
output:
  bookdown::pdf_document2:
    fig_caption: yes
    fig_height: 3
    fig_width: 4
    keep_tex: no
    latex_engine: xelatex
    number_sections: yes
    toc: no
geometry: margin=1in
link-citations: yes
urlcolor: blue
fontsize: 12pt
biblio-style: apalike
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(cache = FALSE, echo = TRUE, message = FALSE, warning = FALSE)
```

<!-- ======================================================================= -->
<!-- ============================== NOTLAR ================================= -->
<!-- ======================================================================= -->
[^1]: 21080360, [Github Repo](https://github.com/kaganglr/AraSinav)


# Giriş

                        Solow Modeli ve Yakınsama Hipotezi
 
Ana akım iktisat`ın büyüme modeli olan Solow-Swan modelinin ülkeler arasındaki gelir eşitsizliklerini açıklama gücü tartışılır, ama (Mankiw-Romer-Weil, 1992)`in ana akım büyüme modeline uyarladıkları genişletilmiş modeli, eşitsizlikleri açıkladığını iddia etmiş ve uyarlanan bu model geniş bir kabul görmüştür.
Ülkeler arasındaki büyük gelir farklılıklarının zaman içinde birbirlerine yaklaşmadığı müşahade edildiğinden teorinin ampirik olarak yanlışlandığı düşünülmüş ve Solow-Swan modelinden çıkış eğilimleri kuvvetlenmişti.
Makalenin yaptığı ana katkı orijinal Solow-Swan modeline insan sermayesini dâhil ederek temel modelle gelir farklılıklarını koşullu yakınsamayla açıklayabilmesidir.
Bu istikamette (Acemoğlu, 2009: 109-112) büyüme`nin sebeplerini yakın sebepler (Proximate Causes) ve temel sebepler (Fundamental Causes) olarak ikiye ayırmış, yakın sebepleri genişletilmiş Solow-Swan modelindeki açıklayıcı ve dışsal değişkenler (fiziksel sermaye-tasarruf, beşeri sermaye, teknoloji ve nüfus) olarak tasnif etmiş, temel sebepler olarak da şans, coğrafya, kültür ve kurumları göstermiştir.
Dolayısıyla, MRW`nin katkılarıyla, ilgi genişletilmiş Solow-Swan modelinin açıklayıcı değişkenleri yerine bu açıklayıcı değişkenleri belirleyen temel sebeplere kaymıştır.
Ders kitabı Solow-Swan modelinin MRW tarafından genişletilerek karmaşık olan gerçek hayatı daha iyi tasvir eder hale getirilmesi, modelin içsel büyüme modelleri lehine tasfiye edilmesini önlemiş ve ana akım araştırmalarının temel modeli olarak kalmasını sağlamıştır.
Bu çalışmada MRW izlenerek Solow-Swan Modeli (Textbook Slow-Swan Model), Genişletilmiş Solow-Swan Modeli (Augmented Solow-Swan Model), Mutlak ve Koşullu Yakınsama hipotezleri (Absolute and Conditional Convergence) panel veri sabit etkiler (Fixed Effects) yöntemiyle test edilmektedir.
Dolayısıyla, bu çalışmamız, ele alınan dönemin yakınlığı, kullanılan değişkenlerin tamamen ana akım modelini esas alması, panel veri kullanılması, gözlem sayısının çokluğu ve özellikle oluşturulan yeni ülke gruplarıyla uygulamalı literatüre önemli bir katkı sağlamaktadır.
Üçüncü bölümde ekonometrik model değişkenlerinin ana akım modelini yansıtabilmesi için MRW`nin kısa bir özeti verilmektedir.
Sonraki üç bölümde Solow-Swan Modeli ve Genişletilmiş Solow-Swan Modelleri kurulmakta ve ampirik modelle veri seti açıklanmaktadır.
Solow-Swan büyüme modeli olarak anılan bu orijinal neoklasik model, ülkelerin işçi başına düşen gelirlerinin zaman içinde aynı düzeye geleceğini öngörmekteydi.
Yakınsama başarısızlığının etkisiyle (Barro, 1989) Solow-Swan modelindeki yapıyı terk ederek büyüme, yatırım ve doğurganlık gibi pek çok değişken arasındaki eşanlı ilişkilere Sarıbaş, H.
Regresyona uygun olan ve doğrudan Solow-Swan modelinden üretilen ilk model MRW`nin çalışmasıdır ve bu çalışma ana akım iktisadının o zamandan beri en temel büyüme regresyonu olarak kabul edilmiştir (Islam, 2003: 319).
Genişletilmiş Solow-Swan modeli olarak anılan bu modele göre yakınsama koşulludur.
MRW`nin çalışmasından sonra Solow-Swan modelinin ekonometrik olarak daha iyi nasıl tahmin edilebileceği üzerinde durulmuş, esas model olan Solow-Swan`ın teorik üstünlüğü ana akım tarafından devam ettirilmiştir.Bu konuda detaylı bilgi almak için atıf yaptığım @saribacs2016ana okunabilir.

        KIRILGAN BEŞLİ EKONOMİLERİ İÇİN YAKINSAMA HİPOTEZİNİN GEÇERLİLİĞİ  Öz Yakınsama hipotezi
        
Neoklasik teoriye dayanan Solow büyüme modeli temelli, göreli yoksul ülkelerin zengin ülkelere kıyasla daha hızlı büyüyeceği varsayımına dayanmaktadır.
Çalışmada kırılgan beşli ülkelerinin kişi başı GSYH`lerinin birbirlerine ve grup içindeki lider ülkeye önce topluca ardından bireysel olarak yakınsayıp yakınsamadığı, 1980-2017 örneklem dönemi için çağdaş panel birim kök testleriyle araştırılmıştır.
Lider ülke olarak seçilen Güney Afrika`ya ülkelerin, Znlamlılık seviyesinde kuvvetli yakınsama gösterdikleri tespit edilmiştir.

Göreceli gelirlerdeki büyük değişikliklerin en çarpıcı örnekleri büyüme mucizeleridir.
Ekonomik büyüme yazınının en çok tartışılan ve araştırma alanı bulan konularından olan yakınsama hipotezi aslında Solow modelinin genel çıkarımıdır.
Az gelişmiş veya gelişmekte olan ülkelerin verimlilikteki artışları, gelişmiş olan ülkelere nazaran daha hızlı olacağı ve bu yolla büyüme farklılıklarının zaman içinde azalıp yakınsamanın gerçekleşeceği ileri sürülmektedir.
Bu noktada, kişi başı geliri düşük olduğu ülkelerin, gelişmiş ülkelere kıyasla daha hızlı büyüyerek onları yakalaması beklenmektedir. Daha detaylı bilgi için : @yilmaz2020kirilgan makalesi okunabilir.


## Çalışmanın Amacı
Yakınsama Hipotezi ile ilgili topladığım makalelerle bu hipotezin doğruluğu hakkında eleştirel bir bakış ortaya sunmaktır.

## Literatür 
Makaleler sırasıyla ; @ceylan2010yakinsama, @saribacs2016ana, @lichtenberg1994testing, @rassekh1998convergence.




\newpage
# Kaynakça {#references}
<div id="refs"></div>

